version: '3.1'

services:

  web:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: registro_alunos
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
