CREATE DATABASE IF NOT EXISTS registro_alunos;

USE registro_alunos;

CREATE TABLE IF NOT EXISTS alunos (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
